# GIF to PNG Frames Uploader
name: Slack test

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *" # every 1min

jobs:
  slack_job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run scripts
        run: |
          node slack.js
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          FOLDERID: ${{ secrets.FOLDERID }}

